spring.profiles.active=default
spring.application.name=reasignacion-service
server.port=8083

# ── Conexión Cloud — Supabase Pooler (Ohio) ──
# Apunta al esquema 'reasignacion' en las opciones de la URL
spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:6543/postgres?sslmode=require&options=-c%20search_path=reasignacion&prepareThreshold=0&preparedStatementCacheQueriesPerConnection=0
spring.datasource.username=postgres.byqsdgspbsowdmysyaal
spring.datasource.password=Proyecto2026
spring.datasource.driver-class-name=org.postgresql.Driver

# ── JPA / Hibernate ──────────────────────────
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Indica a Hibernate que use el esquema 'reasignacion' por defecto
spring.jpa.properties.hibernate.default_schema=reasignacion

# ── Seguridad y Comunicación entre Microservicios ──
app.jwt.secret=RedNorte2024SecretKeyMuySeguraDe256BitsParaJWT
app.jwt.expiration-ms=86400000
app.cors.allowed-origins=http://localhost:4200
# URL local para consultar información de pabellones si es necesario
pabellon.service.url=${PABELLON_SERVICE_URL:http://localhost:8082}

# ── Documentación Swagger ────────────────────
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tryItOutEnabled=true