spring.profiles.active=default
spring.application.name=pabellon-service
server.port=8082

# ── Conexión Cloud — Supabase Pooler (Ohio) ──
# Apunta al esquema 'pabellon' en las opciones de la URL
spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:6543/postgres?sslmode=require&options=-c%20search_path=pabellon&prepareThreshold=0&preparedStatementCacheQueriesPerConnection=0
spring.datasource.username=postgres.byqsdgspbsowdmysyaal
spring.datasource.password=Proyecto2026
spring.datasource.driver-class-name=org.postgresql.Driver

# ── JPA / Hibernate ──────────────────────────
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Indica a Hibernate que use el esquema 'pabellon' por defecto
spring.jpa.properties.hibernate.default_schema=pabellon

# ── Seguridad y Logs ─────────────────────────
app.jwt.secret=RedNorte2024SecretKeyMuySeguraDe256BitsParaJWT
app.jwt.expiration-ms=86400000
app.cors.allowed-origins=http://localhost:4200
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tryItOutEnabled=true