spring.profiles.active=default
spring.application.name=auth-service
server.port=8081

# ── Conexión Cloud — Supabase Pooler (Ohio) ──
# Cambiamos 'search_path=auth' por 'search_path=auth_app'
spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:6543/postgres?sslmode=require&options=-c%20search_path=auth_app&prepareThreshold=0&preparedStatementCacheQueriesPerConnection=0
spring.datasource.username=postgres.byqsdgspbsowdmysyaal
spring.datasource.password=Proyecto2026
spring.datasource.driver-class-name=org.postgresql.Driver

# ── JPA / Hibernate ──────────────────────────
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# CRÍTICO: Cambiamos el esquema por defecto a auth_app
spring.jpa.properties.hibernate.default_schema=auth_app

# ── Seguridad y Logs ─────────────────────────
app.jwt.secret=RedNorte2024SecretKeyMuySeguraDe256BitsParaJWT
app.jwt.expiration-ms=86400000
app.cors.allowed-origins=http://localhost:4200,http://localhost
logging.level.cl.duoc.rednorte=INFO
logging.level.org.springframework.security=WARN
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tryItOutEnabled=true